services:
  sakura:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sakura
    restart: always
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot
    depends_on:
      - sakuradb

  sakuradb:
    image: mongo:latest
    # user: 1000:1000
    container_name: sakuradb
    hostname: sakuradb
    restart: always
    ports:
      - "27017:27017"
    environment:
      # UID: 1000
      # GID: 1000
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: sakuraDB
    volumes:
      - ../sakuradb/db_data:/data/db

volumes:
  db_data:
